package level

const BASE_EXPERIENCE = 1
const COEFFICIENT = 1

// 经验体系设计
// 可获取经验行为有：刷题、刷套题、考试、新增用户题目、看知识点
const (
	EASY      = 0
	MIDDLE    = 1
	HARD      = 2
	HARD_MORE = 3

	// PRIMARY           = 1
	// MIDDLE_RANK       = 2
	// ADVANCED          = 3
	// SENIOR            = 4
	// SPECIALIST        = 5
	// SENIOR_SPECIALIST = 6
	// RESEARCHER        = 7

	// 不同题目经验值
	EASY_EXPERIENCE      = BASE_EXPERIENCE * 2
	MIDDLE_EXPERIENCE    = BASE_EXPERIENCE * 4
	HARD_EXPERIENCE      = BASE_EXPERIENCE * 6
	HARD_MORE_EXPERIENCE = BASE_EXPERIENCE * 8

	// 如果是重点题则 + 基础*3
	IMPORTANT_TOPIC = BASE_EXPERIENCE * 3

	// 难度 * 系数, 这里是系数
	PRIMARY_EXPERIENCE           = COEFFICIENT * 1
	MIDDLE_RANK_EXPERIENCE       = COEFFICIENT * 2
	ADVANCED_EXPERIENCE          = COEFFICIENT * 3
	SENIOR_EXPERIENCE            = COEFFICIENT * 4
	SPECIALIST_EXPERIENCE        = COEFFICIENT * 5
	SENIOR_SPECIALIST_EXPERIENCE = COEFFICIENT * 6
	RESEARCHER_EXPERIENCE        = COEFFICIENT * 7

	// 做错统一只加基础
	MAKE_MISTAKE = BASE_EXPERIENCE

	PRIMARY_EXPERIENCE_UP           = BASE_EXPERIENCE * 2000
	MIDDLE_RANK_EXPERIENCE_UP       = PRIMARY_EXPERIENCE_UP * 3
	ADVANCED_EXPERIENCE_UP          = MIDDLE_RANK_EXPERIENCE_UP * 3.1
	SENIOR_EXPERIENCE_UP            = ADVANCED_EXPERIENCE_UP * 3.2
	SPECIALIST_EXPERIENCE_UP        = SENIOR_EXPERIENCE_UP * 3.4
	SENIOR_SPECIALIST_EXPERIENCE_UP = SPECIALIST_EXPERIENCE_UP * 3.8
	RESEARCHER_EXPERIENCE_UP        = SENIOR_SPECIALIST_EXPERIENCE_UP * 4.6

	// 从高级开始对做的题目难度数量有要求
	// 高级 => 资深  	  初级 50%  中级 50%  高级 30%
	// 资深 => 专家  	  初级 80%  中级 60%  高级 40%  资深 20%
	// 专家 => 资深专家    初级 90%  中级 70%  高级 60%  资深 30%
	// 资深专家 => 研究员  初级 100%  中级 90%  高级 80%  资深 50%
)
