// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "黄日明` + "`" + `",
            "email": "2313773899@qq.com` + "`" + `"
        },
        "license": {
            "name": "Apache 2.0` + "`" + `",
            "url": "[http://www.apache.org/licenses/LICENSE-2.0.html](http://www.apache.org/licenses/LICENSE-2.0.html)` + "`" + `"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/classify/query-classify": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "classify_name",
                        "name": "classify_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "rank",
                        "name": "rank",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "is_use",
                        "name": "is_use",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/classify/query-classify-type": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询分类以及对应二级分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "classify_name",
                        "name": "classify_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "rank",
                        "name": "rank",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "is_use",
                        "name": "is_use",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/company/query-company": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询公司",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "company_name",
                        "name": "company_name",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "is_use",
                        "name": "is_use",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/type/query-type": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询二级分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "classify_name",
                        "name": "classify_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "type_name",
                        "name": "type_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "classify_id",
                        "name": "classify_id",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "is_use",
                        "name": "is_use",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/user-login/layout": {
            "get": {
                "summary": "登出"
            }
        },
        "/api/user-login/wxLogin": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "登陆相关方法,分开两个方法是为了避免以后或许想对应不同端登陆可以做一些不同的操作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "登陆来源",
                        "name": "come_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "登陆方式",
                        "name": "login_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "nick_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/user-login/wxapp-dncrypt": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "微信解密",
                "parameters": [
                    {
                        "type": "string",
                        "description": "rawData",
                        "name": "rawData",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sessionKey",
                        "name": "sessionKey",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "iv",
                        "name": "iv",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/user-login/wxapp-get-openid": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "微信获取openid和session_key,为了数据安全，不应该把session_key返回前端",
                "parameters": [
                    {
                        "type": "string",
                        "description": "openid",
                        "name": "code",
                        "in": "query"
                    }
                ]
            }
        },
        "/api/user/account-manage/binding-phone": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "nick_name",
                        "name": "nick_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "come_from",
                        "name": "come_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gender",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "city",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "province",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "country",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "language",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "is_admin",
                        "name": "is_admin",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "birthday",
                        "name": "birthday",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "create_at",
                        "name": "create_at",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "delete_at",
                        "name": "delete_at",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "update_at",
                        "name": "update_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "is_use",
                        "name": "is_use",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageNum",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ]
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0`",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "项目模版`",
	Description: "为了自己以后方便写点小东西，搭个模版`",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
