// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "黄日明` + "`" + `",
            "email": "2313773899@qq.com` + "`" + `"
        },
        "license": {
            "name": "Apache 2.0` + "`" + `",
            "url": "[http://www.apache.org/licenses/LICENSE-2.0.html](http://www.apache.org/licenses/LICENSE-2.0.html)` + "`" + `"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user-login/wxLogin": {
            "post": {
                "description": "微信登陆",
                "produces": [
                    "application/json"
                ],
                "summary": "登陆相关方法",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 31a165baebe6dec616b1f8f3207b4273",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "openid",
                        "name": "openid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "微信",
                        "name": "come_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "nick_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户头像",
                        "name": "avatar_url",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "性别",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "城市",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "省份",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "国家",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "语言",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "rawdata",
                        "name": "rawdata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "signature",
                        "name": "signature",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "encrypteddata",
                        "name": "encrypteddata",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "iv",
                        "name": "iv",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userLogin.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "userLogin.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0`",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "项目模版`",
	Description: "为了自己以后方便写点小东西，搭个模版`",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
