info:
  contact:
    email: support@swagger.io`
    name: 黄日明 2313773899@qq.com`
    url: '[http://www.swagger.io/support](http://www.swagger.io/support)`'
  description: 为了自己以后方便写点小东西，搭个模版`
  license:
    name: Apache 2.0`
    url: '[http://www.apache.org/licenses/LICENSE-2.0.html](http://www.apache.org/licenses/LICENSE-2.0.html)`'
  termsOfService: '[http://swagger.io/terms/](http://swagger.io/terms/)`'
  title: 项目模版`
  version: 1.0`
paths:
  /api/user-auth/login:
    post:
      parameters:
      - description: account
        in: query
        name: account
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登陆方法
swagger: "2.0"
